### ISSUE TITLE
BPDM Charts and resource quotas

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/bpdm#1222]
I raise this issue to discuss about resource quota definitions for our BPDM Charts deployment as mentioned here:

https://github.com/eclipse-tractusx/bpdm/security/code-scanning/4691

In my opinion we should not add a resource quota or any kind of policy referencing a resource quota in the pods. My reasoning is that we already decided against deploying a fixed namespace with our BPDM Charts and instead make it flexible for the user to deploy BPDM in any namespace they want  (discussion for this see here #1151). Since a resource quota is tied to the actual namespace our deployment should not specify it, we expect it to be handled by the deploying person. That again means, we can't really define a policy in the pods to a non-existing resource quota object. Hence, we should dismiss these issues as not relevant for BPDM.

**Comment by SujitMBRDI** [comment]
Hello @nicoprow,
Since BPDM Charts are designed to be deployed in any namespace, defining `ResourceQuota` and `LimitRange` within the Helm charts may create unnecessary constraints. `ResourceQuota` is inherently namespace-specific, and requiring it in the charts could impose limitations on users who may want to manage these settings separately. Also, we already have resource mentioned. But just as an idea from my side can we do something like below which will be pluggable if some user/enterprise need it, 
Flexible solution -  Users can enable/disable ResourceQuota and LimitRange. 
values mentioned - default false
```
resourceQuota:
  enabled: false
  name: bpdm-resource-quota
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"

limitRange:
  enabled: false
  name: bpdm-limit-range
  limits:
    - type: Container
      max:
        cpu: "1"
        memory: "1Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "500m"
        memory: "256Mi"
      defaultRequest:
        cpu: "200m"
        memory: "128Mi"
      maxLimitRequestRatio:
        cpu: "10"

```

resourcequota.yml
```
{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.resourceQuota.name }}
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    {{- range $key, $value := .Values.resourceQuota.hard }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}

```
Update the resources section to allow users to override defaults:
```
          resources:
            {{- if .Values.resourceQuota.enabled }}
            limits:
              cpu: {{ .Values.resourceQuota.hard.limits.cpu }}
              memory: {{ .Values.resourceQuota.hard.limits.memory }}
            requests:
              cpu: {{ .Values.resourceQuota.hard.requests.cpu }}
              memory: {{ .Values.resourceQuota.hard.requests.memory }}
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
```

Something like this, I haven't tried it but with my wide guess can we give rights to user where they can override settings at deployment time.
