### ISSUE TITLE
TRG 5.09 Helm Test running properly Workflow outdated

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/bpdm#645]
Could please adapt and implement the following workflow that we can check all releated on workflow dispatch?

and would add also the helm upgrade thing in your current workflow

see https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09/

Thanks in advance
``` yaml
name: Lint and Test Charts

on:
    pull_request:
    workflow_dispatch:
      inputs:
        node_image:
          description: 'kindest/node image for k8s kind cluster'
          # k8s version from 3.1 release as default
          default: 'kindest/node:v1.27.3'
          required: false
          type: string
        upgrade_from:
          description: 'chart version to upgrade from'
          # chart version from 3.1 release as default
          default: 'x.x.x'
          required: false
          type: string

jobs:
    lint-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Kubernetes KinD Cluster
              uses: container-tools/kind-action@v1
              with:
                # upgrade version, default (v0.17.0) uses node image v1.21.1 and doesn't work with more recent node image versions
                version: v0.20.0
                # default value for event_name != workflow_dispatch
                node_image: ${{ github.event.inputs.node_image || 'kindest/node:v1.27.3' }}

            - name: Build image
              uses: docker/build-push-action@v3
              with:
                context: .
                push: true
                tags: kind-registry:5000/app-dashboard:testing

            - name: Set up Helm
              uses: azure/setup-helm@v3
              with:
                version: v3.9.3

            - uses: actions/setup-python@v4
              with:
                python-version: '3.9'
                check-latest: true
            - name: Set up chart-testing
              uses: helm/chart-testing-action@v2.3.1

            - name: Run chart-testing (list-changed)
              id: list-changed
              run: |
                changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
                if [[ -n "$changed" ]]; then
                  echo "changed=true" >> $GITHUB_OUTPUT
                fi

            - name: Run chart-testing (lint)
              run: ct lint --validate-maintainers=false --target-branch ${{ github.event.repository.default_branch }}
            - name: Run chart-testing (install)
              run: ct install --charts charts/app-dashboard
              if: github.event_name != 'pull_request' || steps.list-changed.outputs.changed == 'true'

              # Upgrade the released chart version with the locally available chart
              # default value for event_name != workflow_dispatch
            - name: Run helm upgrade
              run: |
                helm repo add bitnami https://charts.bitnami.com/bitnami
                helm repo add tractusx-dev https://eclipse-tractusx.github.io/charts/dev
                helm install [NAME] tractusx-dev/[CHART] --version ${{ github.event.inputs.upgrade_from || 'x.x.x' }}
                helm dependency update charts/[CHART]
                helm upgrade [NAME] charts/[CHART]
              if: github.event_name != 'pull_request' || steps.list-changed.outputs.changed == 'true'
```
