### ISSUE TITLE
[e2e-testing/tutorial] improve helm-chart

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/bpdm#795]
### Description

In order to support [e2e-testing](https://github.com/eclipse-tractusx/e2e-testing/tree/main/charts/umbrella) and tutorial / local setup, I suggest some improvements to the helm-chart.

### Acceptance Criteria

- [x] [BLOCKER FOR INTEGRATION WITH UMBRELLA] solve error when installing with charts that also have a postgresql dependency

I encounter the following error when I install the chart with other that also have a postgresql dependency

```
Error: UPGRADE FAILED: template: umbrella/charts/discoveryfinder/charts/postgresql/templates/primary/svc.yaml:11:14: executing "umbrella/charts/discoveryfinder/charts/postgresql/templates/primary/svc.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: umbrella/charts/bpdm/charts/postgres/charts/common/templates/_labels.tpl:6:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: umbrella/charts/bpdm/charts/postgres/charts/common/templates/_names.tpl:6:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```
Used config:

```
bpdm:
  bpdm-gate:
    postgres:
      nameOverride: "bpdm-postgresql"
  bpdm-pool:
    postgres:
      nameOverride: "bpdm-postgresql"
  bpdm-bridge-dummy:
    enabled: false
  bpdm-cleaning-service-dummy:
    enabled: false
  postgres:
    nameOverride: "bpdm-postgresql"
    enabled: true
```
May be an issue connected to the different postgres (the other charts are on bitnami chart version 12.x.x) version and be addressed by https://github.com/eclipse-tractusx/bpdm/issues/764

- [ ] provide [images](https://hub.docker.com/search?q=tractusx%2Fbpdm) for arm64 cpu arch, [example](https://hub.docker.com/r/tractusx/bpdm-gate/tags) - in addition to amd64 (image doesn't work on newer Macs, this is relevant especially in the tutorial use case)
- [x] set default imagePullPolicy to `IfNotPresent`
- [ ] Suggestion to change the recommended fullnameOverride(s) in the [values.yaml](https://github.com/eclipse-tractusx/bpdm/blob/bpdm-4.0.1/charts/bpdm/values.yaml) to nameOverride(s) - especially in the case when integrating with charts that have the same dependency, unique labels (name) are important

### Additional Information

evaluation done on chart version 4.0.1

cc: @jzbmw
